# -*- coding: utf-8 -*-
"""CSV-DATA-QUERY-TOOL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lf2N05TYtdIENX4Dd6scjtEVG8ANuRnf
"""

import pandas as pd
file=pd.read_csv("/students.csv")
students = file.to_dict(orient="records")

print(file)

all_students=students

top_students=[]
for student in students:
  if student["marks"]>80:
    top_students.append(student)

low_students=[]
for student in students:
  if student["marks"]<50:
    low_students.append(student)

top_student=[max(students,key=lambda x:x["marks"])]
lowest_student=[min(students,key=lambda x:x["marks"])]

total_marks=sum(student["marks"] for student in students)
total_students=len(students)
avg=total_marks/total_students


top_attendee=[]
for student in students:
  if student["attendance"]>80:
    top_attendee.append(student)

low_attendee=[]
for student in students:
  if student["attendance"]<50:
    low_attendee.append(student)

low_attendece_marks=[]
for student in students:
  if student["attendance"]<50 and student["marks"]<50:
    low_attendece_marks.append(student)

top_attendece_marks=[]
for student in students:
  if student["attendance"]>80 and student["marks"]>80:
    top_attendece_marks.append(student)



while True:
 command=input("0:specific student\n1:all students\n2:top students\n3:low students\n"
        "4:top student\n5:lowest student\n6:top attendance\n7:low attendance\n"
        "8:top attendees\n9:low attendees\n10:avg marks\n"
        "11:low attendance & marks\n12:high attendance & marks\n13:exit\n")
 found=False
 if command=="0":
   student_name=input("enter student name")
   for student in students:
     if student["name"].lower()==student_name.lower():
      print(student)
      found=True
   if not found:
      print("studnet not found")

 elif command=="1":
   print(all_students)
 elif command=="2":
   print(top_students)
 elif command=="3":
   print(low_students)
 elif command=="4":
   print(top_student)
 elif command=="5":
   print(lowest_student)
 elif command=="8":
   print(top_attendece_marks)
 elif command=="9":
   print(low_attendece_marks)
 elif command=="6":
   print(top_attendee)
 elif command=="7":
   print(low_attendee)
 elif command=="10":
   print(avg)
 elif command=="11":
   print(low_attendece_marks)
 elif command=="12":
   print(top_attendece_marks)
 elif command=="13":
    break
 else:
   print("invalid command")
